# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - 
    main: cmd/traefik-dashboard/main.go
    binary: traefik-dashboard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch: 
      - amd64
dockers:
  -
    goos: linux
    goarch: amd64
    binaries: 
      - traefik-dashboard
    image_templates: 
    - iwittkau/traefik-dashboard:latest
    - iwittkau/traefik-dashboard:{{ .Version }}
    skip_push: true
    dockerfile: Dockerfile
    extra_files:
      - templates
archive:
  replacements:
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
